source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FlipFlobjc_Example', :exclusive => true do
  pod "FlipFlobjc", :path => "../"
end

target 'FlipFlobjc_Tests', :exclusive => true do
  pod "FlipFlobjc", :path => "../"

  
end
